version: '3'
services:
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_DATABASE=spring_boot_mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=hugo
      - MYSQL_PASSWORD=hugo
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
  sales-server:
    build:
      context: ./
      dockerfile: sales/Dockerfile
    image: sales/server
    ports:
      - "8082:8082"
      - "5005:5005"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - PROFILE=dev
    links:
      - db
#  discovery-server:
#    build:
#      context: ./
#      dockerfile: discovery/Dockerfile
#    image: discovery/server
#    ports:
#      - "8081:8081"
#  gateway-server:
#    build:
#      context: ./
#      dockerfile: gateway/Dockerfile
#    image: gateway/server
#    ports:
#      - "8080:8080"
#    links:
#      - discovery-server
#      - sales-server
#
#  sales-server:
#    build:
#      context: ./
#      dockerfile: sales/Dockerfile
#    image: sales/server
#    ports:
#      - "8082:8082"
#      - "5005:5005"
#    environment:
#      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
#      - PROFILE=dev
#    links:
#      - discovery-server
