server:
  port: 8084

  # Data Base configuration
spring:
  application:
    name: delivery
  datasource:
    url: jdbc:postgresql://127.0.0.1/microservices_java_delivery
    username: hugoiguana
    password: 1234
    platform: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      pool-name: SpringBootMysqlPool
      connection-test-query: select now();
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect # The SQL dialect makes Hibernate generate better SQL for the chosen database
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        input:
          binder: kafka
          destination: microservices-java
          content-type: application/json
          group: input-group-1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: true